In [31]:
# Dataset:

# data = {
#     "Customer": ["Ali", "Sara", "Ali", None, "John"],
#     "Age": [22, None, 22, 25, 30],
#     "City": [" Delhi ", "MUMBAI", " Delhi ", "Chennai", None]
# }

# Tasks:
# identify missing values
# fill missing values
# remove duplicates
# clean city names
# standardize formatting
# check data types
# print cleaned dataset

In [32]:
import pandas as pd
data = {
    "Customer": ["Ali", "Sara", "Ali", None, "John"],
    "Age": [22, None, 22, 25, 30],
    "City": [" Delhi ", "MUMBAI", " Delhi ", "Chennai", None]
}

df = pd.DataFrame(data)
df

  Customer   Age     City
0      Ali  22.0   Delhi
1     Sara   NaN   MUMBAI
2      Ali  22.0   Delhi
3     None  25.0  Chennai
4     John  30.0     None

In [33]:
# identify missing values
df.isnull().sum()

Customer    1
Age         1
City        1
dtype: int64

In [34]:
# fill missing values
df['Customer'] = df['Customer'].fillna('Unknown')

In [35]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [36]:
df['City'] = df['City'].fillna('Unknown')

In [37]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [ ]:
# remove duplicates
df = df.drop_duplicates()

In [40]:
# clean city names
df['City'] = df['City'].str.strip()
# standardize formatting
df['City'] = df['City'].str.lower()

/var/folders/kf/46fvvcgx371d5df6s5n8qp_w0000gn/T/ipykernel_89145/812289832.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City'] = df['City'].str.strip()
/var/folders/kf/46fvvcgx371d5df6s5n8qp_w0000gn/T/ipykernel_89145/812289832.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City'] = df['City'].str.lower()

In [41]:
# check data types
df.dtypes

Customer     object
Age         float64
City         object
dtype: object

In [42]:
# print cleaned dataset
df

  Customer    Age     City
0      Ali  22.00    delhi
1     Sara  24.75   mumbai
3  Unknown  25.00  chennai
4     John  30.00  unknown

In [ ]:
# REAL-WORLD ANALYST THINKING TASK

# Imagine:
# You work in food delivery company.

# Question:
# Why duplicate customers dangerous?
# Why inconsistent city names problematic?
# How can missing data affect business decisions?
# Should analysts always delete missing values?

# Think business-wise.