In [2]:
# Dataset:
# data = {
#     "Name": ["A", "B", None, "D"],
#     "Marks": [90, None, 78, 85]
# }
# Q1
# Find missing values.

In [3]:
import pandas as pd

data = {
    "Name": ["A", "B", None, "D"],
    "Marks": [90, None, 78, 85]
}
df = pd.DataFrame(data)

df.isnull()

    Name  Marks
0  False  False
1  False   True
2   True  False
3  False  False

In [4]:
# Q2
# Count missing values column-wise.
df.isnull().sum()

Name     1
Marks    1
dtype: int64

In [5]:
# Q3
# Fill missing marks with average marks.
df['Marks'].fillna(df['Marks'].mean())

0    90.000000
1    84.333333
2    78.000000
3    85.000000
Name: Marks, dtype: float64

In [6]:
# Q4
# Fill missing names with “Unknown”.

df['Name'].fillna("Unknown")

0          A
1          B
2    Unknown
3          D
Name: Name, dtype: object

In [7]:
df

   Name  Marks
0     A   90.0
1     B    NaN
2  None   78.0
3     D   85.0